[versions]
agp = "9.0.0"
compose-bom = "2026.01.00"
# @keep
android-compileSdk = "36"
# @keep
android-minSdk = "26"
# @keep
android-targetSdk = "36"
konsist = "0.17.3"
kotlin = "2.2.21"
ksp = "2.3.4"
appcompat = "1.7.1"
core-splashscreen = "1.2.0"
core-ktx = "1.17.0"
core-testing = "2.2.0"
lifecycle-runtime-ktx = "2.10.0"
lifecycle-compose = "2.10.0"
activity-compose = "1.12.2"
retrofit = "3.0.0"
hilt = "2.59"
hilt-navigation-compose = "1.3.0"
coil-compose = "2.7.0"
window = "1.5.1"
kotlinx-serialization-json = "1.9.0"
nav-compose = "2.9.6"
gson = "2.13.2"
okio = "3.16.4"
okhttp = "5.3.2"
logging-interceptor = "5.3.2"
timber = "5.0.1"
material = "1.13.0"
lottie-compose = "6.7.1"
androidx-test-ext-junit = "1.3.0"
espresso = "3.7.0"
junitparams = "1.1.1"
junit-jupiter = "5.13.4"
mockk = "1.14.7"
coroutines-test = "1.10.2"
mockwebserver = "5.3.2"
roborazzi = "1.57.0"
robolectric = "4.15"
versions = "0.53.0"
glance = "1.1.1"
glance-experimental = "0.2.2"
test-core = "1.7.0"
junit-platform = "1.13.4"

[libraries]
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-navigation-runtime-ktx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "nav-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
material3 = { group = "androidx.compose.material3", name = "material3" }
material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class" }
navigation-compose = { group = "androidx.navigation", name ="navigation-compose", version.ref = "nav-compose" }
material = { group = "com.google.android.material", name ="material", version.ref = "material" }

lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-compose" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor"}
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie-compose" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }

glance-widget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }

glance-testing = { group = "androidx.glance", name = "glance-testing", version.ref = "glance" }
glance-appwidget-testing = { group = "androidx.glance", name = "glance-appwidget-testing", version.ref = "glance" }

glance-preview = { group = "androidx.glance", name = "glance-preview", version.ref = "glance" }
glance-appwidget-preview = { group = "androidx.glance", name = "glance-appwidget-preview", version.ref = "glance" }
glance-appwidget-host = { group = "com.google.android.glance.tools", name = "appwidget-host", version.ref = "glance-experimental" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-test-core = { group = "androidx.test", name = "core-ktx", version.ref = "test-core" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "test-core" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
junitparams = { group = "pl.pragmatists", name = "JUnitParams", version.ref = "junitparams" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "core-testing" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-jupiter" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockwebserver" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { group = "io.github.takahirom.roborazzi", name = "roborazzi-compose", version.ref = "roborazzi" }
roborazzi-rule = { group = "io.github.takahirom.roborazzi", name = "roborazzi-junit-rule", version.ref = "roborazzi" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
androidx-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-engine", version.ref = "junit-platform" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit-jupiter" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
gradle-versions-plugin = { id = "com.github.ben-manes.versions", version.ref = "versions" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
[bundles]
test-utilities = [
    "androidx-core-testing",
    "konsist",
]
